theme = "term16_dark"

[editor]
line-number = "relative"
true-color = true
rulers = [120]
auto-save = true
text-width = 120
bufferline = "always"
shell = ["zsh", "-c"]
terminal.command = "bash"
terminal.args = ["-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-f = [":new", ":insert-output lf-pick", ":term16_dark", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":term16_dark"]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
C-l = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-d = [":new", ":insert-output lazydocker", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]
center = []
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
